### ISSUE TITLE
Instruction to run frontends locally

### ISSUE THREAD

**Issue by peteryxu** [aws-samples/serverless-coffee-workshop#34]
very good docs in the workshop for backend deployment. It would be nice to provide instruction to deploy the 3 frontends apps as well. This will enable developer to run the three Vue frontends app locally, and even create other React apps, or mobile apps.

**Comment by peteryxu** [comment]
trying to run display app locally, and it won't even start, with error below.  Any insight to share? 

#########
npm run serve

> serverlesspresso@0.1.0 serve
> vue-cli-service serve

 INFO  Starting development server...
10% building 2/3 modules 1 active ...erless-coffee-workshop/frontends/vue-display-app/src/main.jsError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/peteryxu/CODE/JSTS/serverlesspresso/serverless-coffee-workshop/frontends/vue-display-app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/peteryxu/CODE/JSTS/serverlesspresso/serverless-coffee-workshop/frontends/vue-display-app/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/peteryxu/CODE/JSTS/serverlesspresso/serverless-coffee-workshop/frontends/vue-display-app/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/peteryxu/CODE/JSTS/serverlesspresso/serverless-coffee-workshop/frontends/vue-display-app/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/peteryxu/CODE/JSTS/serverlesspresso/serverless-coffee-workshop/frontends/vue-display-app/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/peteryxu/CODE/JSTS/serverlesspresso/serverless-coffee-workshop/frontends/vue-display-app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/peteryxu/CODE/JSTS/serverlesspresso/serverless-coffee-workshop/frontends/vue-display-app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/peteryxu/CODE/JSTS/serverlesspresso/serverless-coffee-workshop/frontends/vue-display-app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/peteryxu/CODE/JSTS/serverlesspresso/serverless-coffee-workshop/frontends/vue-display-app/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/peteryxu/CODE/JSTS/serverlesspresso/serverless-coffee-workshop/frontends/vue-display-app/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/peteryxu/CODE/JSTS/serverlesspresso/serverless-coffee-workshop/frontends/vue-display-app/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/peteryxu/CODE/JSTS/serverlesspresso/serverless-coffee-workshop/frontends/vue-display-app/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/peteryxu/CODE/JSTS/serverlesspresso/serverless-coffee-workshop/frontends/vue-display-app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/peteryxu/CODE/JSTS/serverlesspresso/serverless-coffee-workshop/frontends/vue-display-app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
10% building 2/5 modules 3 active ...tends/vue-display-app/node_modules/webpack/hot/dev-server.jsnode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/peteryxu/CODE/JSTS/serverlesspresso/serverless-coffee-workshop/frontends/vue-display-app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/peteryxu/CODE/JSTS/serverlesspresso/serverless-coffee-workshop/frontends/vue-display-app/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/peteryxu/CODE/JSTS/serverlesspresso/serverless-coffee-workshop/frontends/vue-display-app/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/peteryxu/CODE/JSTS/serverlesspresso/serverless-coffee-workshop/frontends/vue-display-app/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/peteryxu/CODE/JSTS/serverlesspresso/serverless-coffee-workshop/frontends/vue-display-app/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/peteryxu/CODE/JSTS/serverlesspresso/serverless-coffee-workshop/frontends/vue-display-app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/peteryxu/CODE/JSTS/serverlesspresso/serverless-coffee-workshop/frontends/vue-display-app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/peteryxu/CODE/JSTS/serverlesspresso/serverless-coffee-workshop/frontends/vue-display-app/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/peteryxu/CODE/JSTS/serverlesspresso/serverless-coffee-workshop/frontends/vue-display-app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/peteryxu/CODE/JSTS/serverlesspresso/serverless-coffee-workshop/frontends/vue-display-app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/peteryxu/CODE/JSTS/serverlesspresso/serverless-coffee-workshop/frontends/vue-display-app/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.13.0

**Comment by peteryxu** [comment]
barista app won't start:  missing the Print component.  

############
npm run serve

> serverlesspresso@0.1.0 serve
> vue-cli-service serve

 INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 error                                                  9:40:12 PM

This dependency was not found:

* @/components/Printing in ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader-v16/dist??ref--1-1!./src/App.vue?vue&type=script&lang=js

To install it, you can run: npm install --save @/components/Printing

**Comment by bls20AWS** [comment]
The front ends are hosted externally, deploying locally, and support for local running of the frontends is not a part of the workshop,
