### ISSUE TITLE
SanitizeOrderLambda is not working

### ISSUE THREAD

**Issue by khairulhabibataws** [aws-samples/serverless-coffee-workshop#48]
Error on invoke SanitizeOrderLambda

How to reproduce:
Invoke SanitizeOrderLambda from Serverlesspresso event bus test or
Invoke SanitizeOrderLambda directly from Lambda console test page

Expected Result:
Lambda return boolean (true or false)

Current Result:
Got exception:

> 
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'dynamodb-data-types'\nRequire stack:\n- /var/task/app.js\n- /var/runtime/UserFunction.js\n- /var/runtime/Runtime.js\n- /var/runtime/index.js",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 'dynamodb-data-types'",
    "Require stack:",
    "- /var/task/app.js",
    "- /var/runtime/UserFunction.js",
    "- /var/runtime/Runtime.js",
    "- /var/runtime/index.js",
    "    at _loadUserApp (/var/runtime/UserFunction.js:225:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:300:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:34)",
    "    at Module._compile (internal/modules/cjs/loader.js:1114:14)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)",
    "    at Module.load (internal/modules/cjs/loader.js:979:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:819:12)",
    "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)",
    "    at internal/main/run_main_module.js:17:47"
  ]
}

**Comment by bfreiberg** [comment]
Hi, could you please check if this still error occurs with the latest version?
